# Generated by Django 6.0.4 on 2026-06-11 18:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("tagline", models.CharField(blank=True, default="", max_length=200)),
                ("byline", models.CharField(blank=True, default="", max_length=300)),
                ("live_url", models.URLField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("live", "Live"), ("coming-soon", "Coming Soon")],
                        default="live",
                        help_text="Only 'Live' products appear on the public site.",
                        max_length=20,
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Used on the home-page card and products list. Aim for ≤60 words.",
                    ),
                ),
                (
                    "long_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="2-3 paragraphs. Used in the detail page hero. Plain text — line breaks become paragraphs.",
                    ),
                ),
                (
                    "problem_statements",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="One bullet per line. Rendered as the 'What it solves' list.",
                    ),
                ),
                (
                    "target_users",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="One user type per line. Format: 'Type — what they use it for.'",
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of feature dicts: [{"name": "...", "description": "...", "icon": "bi-buildings"}]. Icon is a Bootstrap Icons class name.',
                    ),
                ),
                (
                    "differentiators",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="One per line. Rendered as the 'What makes it different' list.",
                    ),
                ),
                (
                    "how_it_works_steps",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="One step per line. Rendered as a numbered process.",
                    ),
                ),
                (
                    "pricing_summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="1-2 sentences describing how pricing works.",
                    ),
                ),
                (
                    "onboarding_promise",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Single line — e.g. 'Get started in 24 hours.'",
                        max_length=200,
                    ),
                ),
                (
                    "cta_primary_label",
                    models.CharField(blank=True, default="Request a demo", max_length=60),
                ),
                (
                    "cta_primary_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Where the primary CTA points. Usually the live product URL.",
                    ),
                ),
                (
                    "cta_secondary_label",
                    models.CharField(blank=True, default="Take the tour", max_length=60),
                ),
                ("cta_secondary_url", models.URLField(blank=True, default="")),
                ("contact_email", models.EmailField(blank=True, default="", max_length=254)),
                ("contact_phone", models.CharField(blank=True, default="", max_length=30)),
                ("contact_hours", models.CharField(blank=True, default="", max_length=150)),
                ("contact_whatsapp", models.CharField(blank=True, default="", max_length=30)),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="≤60 characters recommended. Falls back to product name if empty.",
                        max_length=70,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="≤155 characters recommended. Falls back to short description if empty.",
                        max_length=200,
                    ),
                ),
                (
                    "hero_image",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Relative path under static/images/, e.g. 'products/pms/hero-dashboard.png'. Copy the file into the corresponding static/images/ folder.",
                        max_length=255,
                    ),
                ),
                (
                    "og_image",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Open Graph share card. Relative path under static/images/.",
                        max_length=255,
                    ),
                ),
                (
                    "logo_image",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional product logo (SVG or PNG). Relative path under static/images/.",
                        max_length=255,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional hex color (e.g. #0F766E) for a subtle product badge.",
                        max_length=7,
                    ),
                ),
                (
                    "screenshots",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of screenshot dicts: [{"image": "products/pms/feature-x.png", "caption": "What this shows"}].',
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["order", "name"],
            },
        ),
    ]
