# Generated by Django 6.0.4 on 2026-06-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remap_pms_icons"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="disclosures",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional honest-tone notes about what's NOT yet shipped — one per line. Rendered as a small 'Currently shipping' callout on the detail page. Leave blank to hide the callout.",
            ),
        ),
    ]
