# Generated by Django 6.0.4 on 2026-05-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_logo_branding_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsSettings",
            fields=[],
            options={
                "verbose_name": "Google Analytics",
                "verbose_name_plural": "Google Analytics",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.sitesettings",),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ga_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Master switch — uncheck to disable analytics site-wide without removing the ID. Tracking is also suppressed automatically when DEBUG is on (local development).",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ga_measurement_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="GA4 Measurement ID (starts with G-). Leave blank to disable tracking.",
                max_length=20,
            ),
        ),
    ]
