# Generated by Django 6.0.4 on 2026-05-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsOverview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Overview",
                "verbose_name_plural": "Overview",
                "default_permissions": (),
            },
        ),
    ]
